services:
  mariadb:
    image: docker.io/mariadb:lts-noble
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  edumfa:
    build: ../..
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - edumfa-keys:/etc/edumfa/:rw
      - ./edumfa-setup.sh:/opt/edumfa/user-scripts/01-setup.sh:ro
      - ./example-policy.py:/opt/edumfa/policy.py:ro
      - ./my-login.html:/opt/edumfa/edumfa-package/static/components/login/views/login.html
      - ./db_password.txt:/etc/edumfa/db_password.txt:ro
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOSTNAME: mariadb
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD_FILE: /etc/edumfa/db_password.txt
      DB_DATABASE: ${MARIADB_DATABASE}
      SECRET_KEY: ${EDUMFA_SECRET_KEY}
      EDUMFA_PEPPER: ${EDUMFA_PEPPER}
      EDUMFA_ADMIN_USER: ${EDUMFA_ADMIN_USER}
      EDUMFA_ADMIN_PASS: ${EDUMFA_ADMIN_PASS}
      EDUMFA_UI_DEACTIVATED: ${EDUMFA_UI_DEACTIVATED}
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  edumfa-keys:
  mariadb-data:
